name: common

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code-checking:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-code-checking
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt,clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: run lint
        run: cargo fmt --check
      - name: run check
        run: cargo check --all-features --tests
      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests

  testing:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-testing
      cancel-in-progress: true
    steps:
      - name: setup docker
        uses: crazy-max/ghaction-setup-docker@v3
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: run tests
        run: cargo test
